---
name: Akwatek
version: 1.0.8
slug: akwatek
description: AKWA Technologies water leak detectors
url: https://github.com/aarnaud/akwatek-hass-addons
image: ghcr.io/aarnaud/akwatek-hass-addons
startup: services
ingress: true
ingress_port: 0
ingress_stream: true
init: false
arch:
  - aarch64
  - amd64
ports:
  8443/tcp: 8443
ports_description:
  8443/tcp: HTTPS port to received controller call
homeassistant_api: false
host_network: true
services:
  - mqtt:want
options:
  tls_port: 8443
  mqtt_data_root_topic: akwatek
  mqtt_discovery_data_topic: homeassistant
schema:
    tls_port: int?
    mqtt_discovery_data_topic: str?
    mqtt_data_root_topic: str?
    mqtt_username: str?
    mqtt_password: password?
    mqtt_server: str?
    mqtt_port: str?
